---
- name: package installation
  hosts: localhost 
  tasks:
  - name: install docker
    apt:
      name='docker'
      state=latest
  - name: service docker
    service:
      name=docker
      state=started
      enabled=yes
